version: "3"

services:
  db:
    build: db
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=animal
      - POSTGRES_USER=maria
      - POSTGRES_PASSWORD=pass
    ports:
      - 5432

  node-srv:
    build: node-srv
    command: /bin/sh -c "/wait && npx prisma db pull && npx ts-node app.ts"
    environment:
      - WAIT_HOSTS=db:5432
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - "80:3000"
